<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Power Audit Report</title>
        <style>
            body {
                font-family: DejaVu Sans, sans-serif;
                font-size: 13px;
                color: #333;
                line-height: 1.5;
            }
            h1 {
                font-size: 22px;
                margin-bottom: 4px;
            }
            h2 {
                font-size: 16px;
                margin-top: 25px;
                margin-bottom: 8px;
                border-bottom: 1px solid #ccc;
                padding-bottom: 3px;
            }
            table {
                width: 100%;
                border-collapse: collapse;
                margin-top: 12px;
            }
            th, td {
                border: 1px solid #ddd;
                padding: 6px 8px;
                text-align: left;
                font-size: 12px;
            }
            th {
                background-color: #f0f0f0;
            }
            .summary p, .setup-info p {
                margin: 4px 0;
            }
            .footer {
                text-align: center;
                font-size: 11px;
                color: #777;
                margin-top: 40px;
                border-top: 1px solid #ccc;
                padding-top: 10px;
            }
        </style>
    </head>
    <body>

        <h1>Power Audit Report</h1>
        <p><strong>Date Generated:</strong> {{ now()->format('d/m/Y') }}</p>

        <h2>Setup Information</h2>
        <div class="setup-info">
            <p><strong>Setup Name:</strong> {{ $setup->name }}</p>
            <p><strong>Created On:</strong> {{ $setup->created_at->format('d/m/Y') }}</p>
            <p><strong>System Voltage:</strong> {{ $setup->system_voltage }}V</p>
            <p><strong>Inverter Efficiency:</strong> {{ $setup->inverter_efficiency }}%</p>
            <p><strong>Battery Type:</strong> {{ ucfirst($setup->battery_type) }} ({{ $setup->battery_type === 'lithium' ? '90%' : '50%' }} usable)</p>
            <p><strong>Autonomy Days:</strong> {{ $setup->autonomy_days }} day(s)</p>
        </div>

        <h2>Appliances</h2>
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Voltage</th>
                    <th>Watts</th>
                    <th>Hours/Day</th>
                    <th>Quantity</th>
                    <th>Wh/Day</th>
                    <th>Ah/Day</th>
                </tr>
            </thead>
            <tbody>
                @foreach($appliances as $a)
                    <tr>
                        <td>{{ $a['name'] }}</td>
                        <td>{{ $a['voltage'] }}V</td>
                        <td>{{ $a['watts'] }}</td>
                        <td>{{ $a['hours'] }}</td>
                        <td>{{ $a['quantity'] }}</td>
                        <td>{{ $a['wh'] }}</td>
                        <td>{{ $a['ah'] }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>

        <h2>Power Summary</h2>
        <div class="summary">
            <p><strong>Total 12V Load:</strong> {{ $nativeAh }} Ah/day</p>
            <p><strong>Total 230V Load:</strong> {{ $inverterAh }} Ah/day (adjusted)</p>
            <p><strong>Inverter Loss:</strong> {{ $lostAh }} Ah/day ({{ $inefficiencyPercent }}% of total usage on this setup)</p>
            <p><strong>Recommended Battery Capacity:</strong> {{ $recommendedAh }} Ah for {{ $setup->autonomy_days }} day(s)</p>
        </div>

        @if(session('power_chart_image'))
        <h2>Ah Usage per Appliance (Chart)</h2>
            <img src="{{ session('power_chart_image') }}" alt="Power Chart" style="max-width:100%;">
        @endif

        @if(session('inverter_chart_image'))
            <h2>Inverter vs Native Load (Chart)</h2>
            <img src="{{ session('inverter_chart_image') }}" alt="Inverter Chart" style="max-width:100%;">
        @endif


        <div class="footer">
            Power Audit Report generated by {{ config('app.name') }} • {{ config('app.url') }}
        </div>
    </body>
</html>
